### ISSUE TITLE
How Can I run withings script ?

### ISSUE THREAD

**Issue by daniel4099** [jtscott/hass-config#1]
Hi, How Can I run withings script, when I update the password and user field. 
How to add the script to home assistant ?

**Comment by jtscott** [comment]
Hi Daniel,

I currently have this configured in HASS as a [command_line sensor](https://home-assistant.io/components/sensor.command_line/). You can see my specific configuration linked below but note that I have [split my configuration files](https://home-assistant.io/topics/splitting_configuration/), so your configuration might be different.

https://github.com/jtscott/hass-config/blob/master/sensor/withings.yaml
