### ISSUE TITLE
Withings - Scripts

### ISSUE THREAD

**Issue by shexbeer** [jtscott/hass-config#5]
Hi iam currently looking at new errors coming from nokia dashboard.
Looks like they changed more things again.

**Comment by shexbeer** [comment]
Ok they changed the endpoint for measurements and associations from
scalews.withings.net
to:
scalews.health.nokia.com

I will make an PR -> https://github.com/jtscott/hass-config/pull/6

**Comment by jtscott** [comment]
Awesome, thanks for the PR!
